### ISSUE TITLE
Install Problem

### ISSUE THREAD

**Issue by josous** [coding-world/Python_DHT#4]
Hy

I have a problem by install the Python_DHT on my Rasperry Pi.
The following error message appears in the terminal.
Can someone help me?
Thank you very much.

Josous

```
pi@raspberrypi ~/Python_DHT $ sudo python3 setup.py install
Downloading https://pypi.python.org/packages/source/s/setuptools/setuptools-4.0.1.zip
Extracting in /tmp/tmpcq8u6e28
Traceback (most recent call last):
  File "/home/pi/Python_DHT/ez_setup.py", line 142, in use_setuptools
    pkg_resources.require("setuptools>=" + version)
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 745, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 639, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: setuptools>=4.0.1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "setup.py", line 2, in <module>
    use_setuptools()
  File "/home/pi/Python_DHT/ez_setup.py", line 145, in use_setuptools
    return _do_download(version, download_base, to_dir, download_delay)
  File "/home/pi/Python_DHT/ez_setup.py", line 120, in _do_download
    _build_egg(egg, archive, to_dir)
  File "/home/pi/Python_DHT/ez_setup.py", line 62, in _build_egg
    with archive_context(archive_filename):
  File "/usr/lib/python3.4/contextlib.py", line 59, in __enter__
    return next(self.gen)
  File "/home/pi/Python_DHT/ez_setup.py", line 100, in archive_context
    with ContextualZipFile(filename) as archive:
  File "/home/pi/Python_DHT/ez_setup.py", line 88, in __new__
    return zipfile.ZipFile(*args, **kwargs)
  File "/usr/lib/python3.4/zipfile.py", line 937, in __init__
    self._RealGetContents()
  File "/usr/lib/python3.4/zipfile.py", line 978, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file
```

**Comment by kracherl** [comment]
maybe try:
`sudo apt-get install python3-setuptools`

The link in ez_setup.py seems old and does not longer exist.

**Comment by josous** [comment]
Hy kracherl

I thank you very much. 

It works now
