### ISSUE TITLE
Probleme mit Installation 

### ISSUE THREAD

**Issue by pingpank** [coding-world/Python_DHT#5]
Hey,
nach dem Ausführen von `sudo python3 setup.py install`
gemäß dem Handbuch bekomme ich folgende Meldung:

```

Extracting in /tmp/tmpqxgk0y1v
Traceback (most recent call last):
  File "/home/pi/Python_DHT/ez_setup.py", line 142, in use_setuptools
    pkg_resources.require("setuptools>=" + version)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 900, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 786, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'setuptools>=4.0.1' distribution was not found and is required by the application

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "setup.py", line 2, in <module>
    use_setuptools()
  File "/home/pi/Python_DHT/ez_setup.py", line 145, in use_setuptools
    return _do_download(version, download_base, to_dir, download_delay)
  File "/home/pi/Python_DHT/ez_setup.py", line 120, in _do_download
    _build_egg(egg, archive, to_dir)
  File "/home/pi/Python_DHT/ez_setup.py", line 62, in _build_egg
    with archive_context(archive_filename):
  File "/usr/lib/python3.7/contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "/home/pi/Python_DHT/ez_setup.py", line 100, in archive_context
    with ContextualZipFile(filename) as archive:
  File "/home/pi/Python_DHT/ez_setup.py", line 88, in __new__
    return zipfile.ZipFile(*args, **kwargs)
  File "/usr/lib/python3.7/zipfile.py", line 1222, in __init__
    self._RealGetContents()
  File "/usr/lib/python3.7/zipfile.py", line 1289, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file
```

Kann ich damit trotzdem weitermachen oder könnt ihr mir dabei helfen?

Liebe Grüße

**Comment by pingpank** [comment]
`
sudo apt-get install python3-setuptools`

War die Lösung...
