### ISSUE TITLE
Kompatibilität mit Raspi 4

### ISSUE THREAD

**Issue by pingpank** [coding-world/Python_DHT#6]
Hallo,
ich bekomme bei dem Versuch die dht11_einfach.py via `python3 dht11_einfach.py`
auszuführen die folgende Fehlermeldung:

```
python3 dht11_einfach.py
Traceback (most recent call last):
  File "dht11_einfach.py", line 5, in <module>
    feuchtigkeit, temperatur = Python_DHT.read_retry(sensor, pin)
  File "/home/pi/Python_DHT/Python_DHT/common.py", line 90, in read_retry
    humidity, temperature = read(sensor, pin, platform)
  File "/home/pi/Python_DHT/Python_DHT/common.py", line 76, in read
    platform = get_platform()
  File "/home/pi/Python_DHT/Python_DHT/common.py", line 51, in get_platform
    import Python_DHT.Raspberry_Pi_2 as Raspberry_Pi_2
  File "/home/pi/Python_DHT/Python_DHT/Raspberry_Pi_2.py", line 22, in <module>
    import Python_DHT.Raspberry_Pi_2_Driver as driver
ModuleNotFoundError: No module named 'Python_DHT.Raspberry_Pi_2_Driver'
```

Gibt es die Möglichkeit, das Ganze auf einem Raspi4 zum laufen zu bringen?

**Comment by ertagh** [comment]
Ich schreib die Antwort mal auf Englisch..

I was wondering the same, so I took a look inside the code.
It seems that you just have to edit 1 line:

Python_DHT/platform_detect.py -> line 99
Add " or match.group(1) == 'BCM2711'" to add the CPU of the RPi 4

After this run setup.py install and it seems to work..
